-- database: ../Database/triv.sqlite
/*
-------------------------------------------
(©) 2k24 EPN-FIS, ALL rights reserved.

-------------------------------------------
Fecha   : 09.enero.2k26
Script  : Insertando Datos en las Tablas
*/

INSERT INTO UserType
    (   Name             ,Description                              ) VALUES
    (   'Player'         ,'Who plays the game'                     )
   ,(   'Admin'          ,'Who administrates the database'         );


INSERT INTO Administrator
    (   idUserType       ,UserName             ,Password           ) VALUES
    (   2                ,'InFismal'           ,'NoSeVale'         )
   ,(   2                ,'Bachily'            ,'2725'             )
   ,(   2                ,'Pandy_06'           ,'queti'            )
   ,(   2                ,'Grandote4x4'        ,'toyota'           )
   ,(   2                ,'KarliBoo'           ,'iCarly'           );


INSERT INTO Category
    (   Name             ,Description                              ) VALUES
    (   'Cultura General','Preguntas de cultura general'           )
   ,(   'Disney'         ,'Preguntas sobre películas Disney'       )
   ,(   'Electronica'    ,'Preguntas sobre electrónica'            )
   ,(   'Planetas'       ,'Preguntas sobre el sistema solar'       )
   ,(   'Tipo de Dato'   ,'Preguntas sobre tipos de datos Java'    );


INSERT INTO Question
    (   idCategory       ,Question                                                                       ) VALUES
    (   1                ,'¿Cuál es el océano más grande del mundo?'                                     ) 
   ,(   1                ,'¿En qué continente se encuentra Egipto?'                                      )
   ,(   1                ,'¿Cuál es el planeta más cercano al Sol?'                                      )
   ,(   1                ,'¿Quién pintó la Mona Lisa?'                                                   )
   ,(   1                ,'¿Cuál es la capital de Japón?'                                                )  
   ,(   1                ,'¿Qué gas es esencial para que los humanos puedan respirar?'                   )
   ,(   1                ,'¿Qué animal es conocido como "el rey de la selva"?'                           )
   ,(   1                ,'¿En qué país se encuentra la Torre Eiffel?'                                   )
   ,(   1                ,'¿Cuál es el río más largo del mundo según estudios recientes?'                )
   ,(   1                ,'¿Qué científico propuso la teoría de la relatividad?'                         )
   ,(   2                ,'¿En qué película aparece el personaje Stich?'                                 ) 
   ,(   2                ,'¿Quién es la mejor amiga de Moana además de Maui?'                            )
   ,(   2                ,'¿Qué princesa tiene un camaleón como mascota?'                                )
   ,(   2                ,'¿En qué película aparece el villano Hades?'                                   )
   ,(   2                ,'¿Cómo se llama el papá de Nemo en Buscando a Nemo?'                           )  
   ,(   2                ,'¿Quién es el dueño de Buzz Lightyear en Toy Story?'                           )
   ,(   2                ,'¿Qué princesa canta "Libre soy"?'                                             )
   ,(   2                ,'¿En qué película sale el personaje Miguel Rivera?'                            )
   ,(   2                ,'¿Cómo se llama el villano de 101 Dálmatas?'                                   )
   ,(   2                ,'¿Qué animal es la mascota de Mulán?'                                          )
   ,(   3                ,'¿Qué es la corriente eléctrica?'                                              ) 
   ,(   3                ,'¿Cuál es la unidad de resistencia eléctrica?'                                 )
   ,(   3                ,'La Ley de Ohm establece la relación entre:'                                   )
   ,(   3                ,'¿Qué componente almacena energía en forma de campo eléctrico?'                )
   ,(   3                ,'¿Cuál es la función principal de un diodo?'                                   )  
   ,(   3                ,'¿Cómo se calcula la potencia eléctrica?'                                      )
   ,(   3                ,'¿En qué unidad se mide la capacitancia?'                                      )
   ,(   3                ,'¿Qué tipo de corriente cambia constantemente de dirección?'                   )
   ,(   3                ,'Un circuito en serie se caracteriza porque:'                                  )
   ,(   3                ,'¿Qué magnitud indica la oposición al cambio de corriente en una bobina?'      )
   ,(   4                ,'¿Cuál es el planeta del sistema solar que se le conoce como Planeta Rojo?'    ) 
   ,(   4                ,'¿Cuál es la distancia aproximada entre la tierra y el sol en kilometros?'     )
   ,(   4                ,'¿Cuál es el planeta gaseoso más grande del sistema solar?'                    )
   ,(   4                ,'¿Cuántas lunas tiene Jupiter?'                                                )
   ,(   4                ,'¿Cuál es el planeta más cercano al sol?'                                      )  
   ,(   4                ,'¿Cuál es la clasificación espectral del sol?'                                 )
   ,(   4                ,'¿Qué singifica Afelio en cuanto a distancia de la tierra con el sol?'         )
   ,(   4                ,'¿Cuál es el planeta clasificado más lejano al sol?'                           )
   ,(   4                ,'¿Cuál de los siguiente planetas enanos existen en el sistema solar?'          )
   ,(   4                ,'¿Cuál es el segundo planeta clasificado más pequeño del sistema solar?'       )
   ,(   5                ,'¿Cuál de los siguientes es un tipo de dato primitivo en Java?'                ) 
   ,(   5                ,'¿Cuál es el tamaño en bits del tipo int en Java?'                             )
   ,(   5                ,'¿Cuál de los siguientes tipos se utiliza para representar un solo carácter?' )
   ,(   5                ,'¿Cuál es el valor por defecto de un boolean?'                                )
   ,(   5                ,'¿Cuál tipo de dato permite almacenar números enteros más grandes que int?'   )  
   ,(   5                ,'¿Cuál de los siguientes es un tipo de dato de punto flotante?'               )
   ,(   5                ,'¿Qué tipo de dato se usa para almacenar texto en Java?'                      )
   ,(   5                ,'¿Cuál de estos tipos NO es primitivo?'                                       )
   ,(   5                ,'¿Qué tipo de dato usarías para almacenar el número 300?'                     )
   ,(   5                ,'¿Cuál es el valor mínimo que puede almacenar un byte?'                       );


INSERT INTO Answer
    (   idQuestion       ,Answer                                                                    ,CorrectAns    ) VALUES
    (   1                ,'Atlántico'                                                               ,'0'           )
   ,(   1                ,'Pacífico'                                                                ,'1'           )
   ,(   1                ,'Índico'                                                                  ,'0'           )
   ,(   1                ,'Ártico'                                                                  ,'0'           )
   ,(   2                ,'Europa'                                                                  ,'0'           )
   ,(   2                ,'América'                                                                 ,'0'           )
   ,(   2                ,'África'                                                                  ,'1'           )
   ,(   2                ,'Asia'                                                                    ,'0'           )
   ,(   3                ,'Venus'                                                                   ,'0'           )
   ,(   3                ,'Marte'                                                                   ,'0'           )
   ,(   3                ,'Mercurio'                                                                ,'1'           )
   ,(   3                ,'Júpiter'                                                                 ,'0'           )
   ,(   4                ,'Miguel Ángel'                                                            ,'0'           )
   ,(   4                ,'Leonardo da Vinci'                                                       ,'1'           )
   ,(   4                ,'Botticelli'                                                              ,'0'           )
   ,(   4                ,'Rafael'                                                                  ,'0'           )
   ,(   5                ,'Osaka'                                                                   ,'0'           )
   ,(   5                ,'Tokio'                                                                   ,'1'           )
   ,(   5                ,'Nagoya'                                                                  ,'0'           )
   ,(   5                ,'Kioto'                                                                   ,'0'           )
   ,(   6                ,'Dióxido de carbono'                                                      ,'0'           )
   ,(   6                ,'Oxígeno'                                                                 ,'1'           )
   ,(   6                ,'Nitrógeno'                                                               ,'0'           )
   ,(   6                ,'Helio'                                                                   ,'0'           )
   ,(   7                ,'Tigre'                                                                   ,'0'           )
   ,(   7                ,'León'                                                                    ,'1'           )
   ,(   7                ,'Jaguar'                                                                  ,'0'           )
   ,(   7                ,'Elefante'                                                                ,'0'           )
   ,(   8                ,'Francia'                                                                 ,'1'           )
   ,(   8                ,'Italia'                                                                  ,'0'           )
   ,(   8                ,'España'                                                                  ,'0'           )
   ,(   8                ,'Alemania'                                                                ,'0'           )
   ,(   9                ,'Nilo'                                                                    ,'0'           )
   ,(   9                ,'Amazonas'                                                                ,'1'           )
   ,(   9                ,'Yangtsé'                                                                 ,'0'           )
   ,(   9                ,'Misisipi'                                                                ,'0'           )
   ,(   10               ,'Newton'                                                                  ,'0'           )
   ,(   10               ,'Einstein'                                                                ,'1'           )
   ,(   10               ,'Galileo'                                                                 ,'0'           )
   ,(   10               ,'Tesla'                                                                   ,'0'           )
   ,(   11               ,'Lilo & Stitch'                                                           ,'1'           )
   ,(   11               ,'Moana'                                                                   ,'0'           )
   ,(   11               ,'Enredados'                                                               ,'0'           )
   ,(   11               ,'Frozen'                                                                  ,'0'           )
   ,(   12               ,'Pua'                                                                     ,'0'           )
   ,(   12               ,'Pascal'                                                                  ,'0'           )
   ,(   12               ,'Flounder'                                                                ,'0'           )
   ,(   12               ,'Dory'                                                                    ,'1'           )
   ,(   13               ,'Tiana'                                                                   ,'0'           )
   ,(   13               ,'Ariel'                                                                   ,'0'           )
   ,(   13               ,'Rapunzel'                                                                ,'1'           )
   ,(   13               ,'Bella'                                                                   ,'0'           )
   ,(   14               ,'La Sirenita'                                                             ,'0'           )
   ,(   14               ,'Aladdín'                                                                 ,'0'           )
   ,(   14               ,'Hércules'                                                                ,'1'           )
   ,(   14               ,'Mulán'                                                                   ,'0'           )
   ,(   15               ,'Bubbles'                                                                 ,'0'           )
   ,(   15               ,'Bruce'                                                                   ,'0'           )
   ,(   15               ,'Marlin'                                                                  ,'1'           )
   ,(   15               ,'Gill'                                                                    ,'0'           )
   ,(   16               ,'Sid'                                                                     ,'0'           )
   ,(   16               ,'Andy'                                                                    ,'1'           )
   ,(   16               ,'Bonnie'                                                                  ,'0'           )
   ,(   16               ,'Carl'                                                                    ,'0'           )
   ,(   17               ,'Elsa'                                                                    ,'1'           )
   ,(   17               ,'Ariel'                                                                   ,'0'           )
   ,(   17               ,'Aurora'                                                                  ,'0'           )
   ,(   17               ,'Jasmín'                                                                  ,'0'           )
   ,(   18               ,'Coco'                                                                    ,'1'           )
   ,(   18               ,'Encanto'                                                                 ,'0'           )
   ,(   18               ,'Ratatouille'                                                             ,'0'           )
   ,(   18               ,'Soul'                                                                    ,'0'           )
   ,(   19               ,'Maléfica'                                                                ,'0'           )
   ,(   19               ,'Cruella de Vil'                                                          ,'1'           )
   ,(   19               ,'Úrsula'                                                                  ,'0'           )
   ,(   19               ,'Yzma'                                                                    ,'0'           )
   ,(   20               ,'Un dragón'                                                               ,'0'           )
   ,(   20               ,'Un caballo'                                                              ,'1'           )
   ,(   20               ,'Un tigre'                                                                ,'0'           )
   ,(   20               ,'Un búho'                                                                 ,'0'           )
   ,(   21               ,'La energía almacenada en un capacitor'                                   ,'0'           )
   ,(   21               ,'El flujo de electrones por un conductor'                                 ,'1'           )
   ,(   21               ,'La diferencia de potencial entre dos puntos'                             ,'0'           )
   ,(   21               ,'La oposición al paso de la corriente'                                    ,'0'           )
   ,(   22               ,'Amperio'                                                                 ,'0'           )
   ,(   22               ,'Voltio'                                                                  ,'0'           )
   ,(   22               ,'Ohmio'                                                                   ,'1'           )
   ,(   22               ,'Watt'                                                                    ,'0'           )
   ,(   23               ,'Resistencia y potencia'                                                  ,'0'           )
   ,(   23               ,'Voltaje, corriente y resistencia'                                        ,'1'           )
   ,(   23               ,'Capacitancia e inductancia'                                              ,'0'           )
   ,(   23               ,'Voltaje y frecuencia'                                                    ,'0'           )
   ,(   24               ,'Resistor'                                                                ,'0'           )
   ,(   24               ,'Inductor'                                                                ,'0'           )
   ,(   24               ,'Diodo'                                                                   ,'0'           )
   ,(   24               ,'Capacitor'                                                               ,'1'           )
   ,(   25               ,'Almacenar energía'                                                       ,'0'           )
   ,(   25               ,'Amplificar señales'                                                      ,'0'           )
   ,(   25               ,'Permitir el paso de corriente en un solo sentido'                        ,'1'         )
   ,(   25               ,'Reducir voltaje'                                                         ,'0'           )
   ,(   26               ,'P = V / I'                                                               ,'0'           )
   ,(   26               ,'P = V x I'                                                               ,'1'           )
   ,(   26               ,'P = I² / R'                                                              ,'0'           )
   ,(   26               ,'P = R x V'                                                               ,'0'           )
   ,(   27               ,'Henry'                                                                   ,'0'           )
   ,(   27               ,'Faradio'                                                                 ,'1'           )
   ,(   27               ,'Tesla'                                                                   ,'0'           )
   ,(   27               ,'Coulomb'                                                                 ,'0'           )
   ,(   28               ,'Corriente continua (DC)'                                                 ,'0'           )
   ,(   28               ,'Corriente alterna (AC)'                                                  ,'1'           )
   ,(   28               ,'Corriente de fuga'                                                       ,'0'           )
   ,(   28               ,'Corriente de pico'                                                       ,'0'           )
   ,(   29               ,'La corriente se divide en diferentes caminos'                            ,'0'          )
   ,(   29               ,'El voltaje es igual en todos los componentes'                            ,'0'          )
   ,(   29               ,'Los componentes comparten la misma corriente'                            ,'1'          )
   ,(   29               ,'No existe resistencia total'                                             ,'0'          )
   ,(   30               ,'Resistencia'                                                             ,'0'           )
   ,(   30               ,'Capacitancia'                                                            ,'0'           )
   ,(   30               ,'Inductancia'                                                             ,'1'           )
   ,(   30               ,'Conductancia'                                                            ,'0'           )
   ,(   31               ,'Urano'                                                                   ,'0'           )
   ,(   31               ,'Neptuno'                                                                 ,'0'           )
   ,(   31               ,'Marte'                                                                   ,'1'           )
   ,(   31               ,'Tierra'                                                                  ,'0'           )
   ,(   32               ,'150,000,000'                                                             ,'1'           )
   ,(   32               ,'100,000'                                                                 ,'0'           )
   ,(   32               ,'150,000'                                                                 ,'0'           )
   ,(   32               ,'100,000,000'                                                             ,'0'           )
   ,(   33               ,'Tierra'                                                                  ,'0'           )
   ,(   33               ,'Mercurio'                                                                ,'0'           )
   ,(   33               ,'Urano'                                                                   ,'0'           )
   ,(   33               ,'Jupiter'                                                                 ,'1'           )
   ,(   34               ,'89'                                                                      ,'0'           )
   ,(   34               ,'70'                                                                      ,'1'           )
   ,(   34               ,'95'                                                                      ,'0'           )
   ,(   34               ,'10'                                                                      ,'0'           )
   ,(   35               ,'Venus'                                                                   ,'0'           )
   ,(   35               ,'Mercurio'                                                                ,'1'           )
   ,(   35               ,'Tierra'                                                                  ,'0'           )
   ,(   35               ,'Saturno'                                                                 ,'0'           )
   ,(   36               ,'M'                                                                       ,'0'           )
   ,(   36               ,'G'                                                                       ,'1'           )
   ,(   36               ,'K'                                                                       ,'0'           )
   ,(   36               ,'O'                                                                       ,'0'           )
   ,(   37               ,'El punto intermedio entre el punto más lejano y cercano'                 ,'0'          )
   ,(   37               ,'El punto mas cercano'                                                    ,'0'           )
   ,(   37               ,'El punto mas lejano'                                                     ,'1'           )
   ,(   37               ,'La distancia no existe, es producto de tu imaginación'                   ,'0'           )
   ,(   38               ,'Saturno'                                                                 ,'0'           )
   ,(   38               ,'Jupiter'                                                                 ,'0'           )
   ,(   38               ,'Neptuno'                                                                 ,'1'           )
   ,(   38               ,'Pluton'                                                                  ,'0'           )
   ,(   39               ,'Ceres'                                                                   ,'1'           )
   ,(   39               ,'Xenor'                                                                   ,'0'           )
   ,(   39               ,'Gesto'                                                                   ,'0'           )
   ,(   39               ,'Etumu'                                                                   ,'0'           )
   ,(   40               ,'Pluton'                                                                  ,'0'           )
   ,(   40               ,'Mercurio'                                                                ,'1'           )
   ,(   40               ,'Tierra'                                                                  ,'0'           )
   ,(   40               ,'Venus'                                                                   ,'0'           )
   ,(   41               ,'String'                                                                  ,'0'           )
   ,(   41               ,'Integer'                                                                 ,'0'           )
   ,(   41               ,'double'                                                                  ,'1'           )
   ,(   41               ,'Scanner'                                                                 ,'0'           )
   ,(   42               ,'8 bits'                                                                  ,'0'           )
   ,(   42               ,'16 bits'                                                                 ,'0'           )
   ,(   42               ,'32 bits'                                                                 ,'1'           )
   ,(   42               ,'64 bits'                                                                 ,'0'           )
   ,(   43               ,'String'                                                                  ,'0'           )
   ,(   43               ,'char'                                                                    ,'1'           )
   ,(   43               ,'Character'                                                               ,'0'           )
   ,(   43               ,'byte'                                                                    ,'0'           )
   ,(   44               ,'true'                                                                    ,'0'           )
   ,(   44               ,'false'                                                                   ,'1'           )
   ,(   44               ,'0'                                                                       ,'0'           )
   ,(   44               ,'null'                                                                    ,'0'           )
   ,(   45               ,'short'                                                                   ,'0'           )
   ,(   45               ,'byte'                                                                    ,'0'           )
   ,(   45               ,'long'                                                                    ,'1'           )
   ,(   45               ,'float'                                                                   ,'0'           )
   ,(   46               ,'long'                                                                    ,'0'           )
   ,(   46               ,'float'                                                                   ,'1'           )
   ,(   46               ,'short'                                                                   ,'0'           )
   ,(   46               ,'boolean'                                                                 ,'0'           )
   ,(   47               ,'char[]'                                                                  ,'0'           )
   ,(   47               ,'String'                                                                  ,'1'           )
   ,(   47               ,'Character'                                                               ,'0'           )
   ,(   47               ,'Text'                                                                    ,'0'           )
   ,(   48               ,'boolean'                                                                 ,'0'           )
   ,(   48               ,'char'                                                                    ,'0'           )
   ,(   48               ,'double'                                                                  ,'0'           )
   ,(   48               ,'String'                                                                  ,'1'           )
   ,(   49               ,'byte'                                                                    ,'0'           )
   ,(   49               ,'short'                                                                   ,'1'           )
   ,(   49               ,'int'                                                                     ,'0'           )
   ,(   49               ,'boolean'                                                                 ,'0'           )
   ,(   50               ,'0'                                                                       ,'0'           )
   ,(   50               ,'-128'                                                                    ,'1'           )
   ,(   50               ,'-255'                                                                    ,'0'           )
   ,(   50               ,'-32768'                                                                  ,'0'           );

   SELECT Question FROM Question WHERE idCategory = 2;
