-- database: ../DataBase/triv.sqlite
/*
-------------------------------------------
(©) 2k24 EPN-FIS, ALL rights reserved.

-------------------------------------------
Fecha   : 09.enero.2k26
Script  : Insertando Tablas
*/

INSERT INTO UserType
    (   Name     ,Description                                                                                     ) VALUES
    (   Player   ,Who plays the game                                                                              )
   ,(   Admin    ,Who administrates the database                                                                  );


INSERT INTO Admin
 (   idUserType     ,UserName       ,Password                                                               ) VALUES
 (   2              ,InFismal       ,NoSeVale                                                               )
,(   2              ,Bachily        ,2725                                                               )
,(   2              ,Pandy_06       ,queti                                                               )
,(   2              ,Grandote4x4    ,toyota                                                               )
,(   2              ,KarliBoo       ,iCarly                                                                 );


INSERT INTO Category
     (   Descript                                                                                        ) VALUES
    ,(   Cultura General)
    ,(   Disney)
    ,(   Electronica)
    ,(   Planetas)
    ,(   Tipo de Dato);
    


INSERT INTO Question
    (   idCategory                 ,Question                                                                            ) VALUES
    (       1                      ,'¿Cuál es el océano más grande del mundo?'                                          ) 
   ,(       1                      ,'¿En qué continente se encuentra Egipto?'                                           )
   ,(       1                      ,'¿Cuál es el planeta más cercano al Sol?'                                           )
   ,(       1                      ,'¿Quién pintó la Mona Lisa?'                                                        )
   ,(       1                      ,'¿Cuál es la capital de Japón?'                                                     )  
   ,(       1                      ,'¿Qué gas es esencial para que los humanos puedan respirar?'                        )
   ,(       1                      ,'¿Qué animal es conocido como "el rey de la selva"?'                                )
   ,(       1                      ,'¿En qué país se encuentra la Torre Eiffel?'                                        )
   ,(       1                      ,'¿Cuál es el río más largo del mundo según estudios recientes?'                     )
   ,(       1                      ,'¿Qué científico propuso la teoría de la relatividad?'                              )

   ,(       2                      ,'¿En qué película aparece el personaje Stich?'                                      ) 
   ,(       2                      ,'¿Quién es la mejor amiga de Moana además de Maui?'                                 )
   ,(       2                      ,'¿Qué princesa tiene un camaleón como mascota?'                                     )
   ,(       2                      ,'¿En qué película aparece el villano Hades?'                                        )
   ,(       2                      ,'¿Cómo se llama el papá de Nemo en Buscando a Nemo?'                                )  
   ,(       2                      ,'¿Quién es el dueño de Buzz Lightyear en Toy Story?'                                )
   ,(       2                      ,'¿Qué princesa canta "Libre soy"?'                                                  )
   ,(       2                      ,'¿En qué película sale el personaje Miguel Rivera?'                                 )
   ,(       2                      ,'¿Cómo se llama el villano de 101 Dálmatas?'                                        )
   ,(       2                      ,'¿Qué animal es la mascota de Mulán?'                                               )

   ,(       3                      ,'¿Qué es la corriente eléctrica?'                                                   ) 
   ,(       3                      ,'¿Cuál es la unidad de resistencia eléctrica?'                                      )
   ,(       3                      ,'La Ley de Ohm establece la relación entre:'                                        )
   ,(       3                      ,'¿Qué componente almacena energía en forma de campo eléctrico?'                     )
   ,(       3                      ,'¿Cuál es la función principal de un diodo?'                                        )  
   ,(       3                      ,'¿Cómo se calcula la potencia eléctrica?'                                           )
   ,(       3                      ,'¿En qué unidad se mide la capacitancia?'                                           )
   ,(       3                      ,'¿Qué tipo de corriente cambia constantemente de dirección?'                        )
   ,(       3                      ,'Un circuito en serie se caracteriza porque:'                                       )
   ,(       3                      ,'¿Qué magnitud indica la oposición al cambio de corriente en una bobina?'           )

   ,(       4                      ,'¿Cuál es el planeta del sistema solar que se le conoce como Planeta Rojo?'         ) 
   ,(       4                      ,'¿Cuál es la distancia aproximada entre la tierra y el sol en kilometros?'          )
   ,(       4                      ,'¿Cuál es el planeta gaseoso más grande del sistema solar?'                         )
   ,(       4                      ,'¿Cuántas lunas tiene Jupiter?'                                                     )
   ,(       4                      ,'¿Cuál es el planeta más cercano al sol?'                                           )  
   ,(       4                      ,'¿Cuál es la clasificación espectral del sol?'                                      )
   ,(       4                      ,'¿Qué singifica Afelio en cuanto a distancia de la tierra con el sol?'              )
   ,(       4                      ,'¿Cuál es el planeta clasificado más lejano al sol?'                                )
   ,(       4                      ,'¿Cuál de los siguiente planetas enanos existen en el sistema solar?'               )
   ,(       4                      ,'¿Cuál es el segundo planeta clasificado más pequeño del sistema solar?'            )

   ,(       5                      ,'¿Cuál de los siguientes es un tipo de dato primitivo en Java?'                     ) 
   ,(       5                      ,'¿Cuál es el tamaño en bits del tipo int en Java?'                                  )
   ,(       5                      ,'¿Cuál de los siguientes tipos se utiliza para representar un solo carácter?'       )
   ,(       5                      ,'¿Cuál es el valor por defecto de un boolean?'                                      )
   ,(       5                      ,'¿Cuál tipo de dato permite almacenar números enteros más grandes que int?'         )  
   ,(       5                      ,'¿Cuál de los siguientes es un tipo de dato de punto flotante?'                     )
   ,(       5                      ,'¿Qué tipo de dato se usa para almacenar texto en Java?'                            )
   ,(       5                      ,'¿Cuál de estos tipos NO es primitivo?'                                             )
   ,(       5                      ,'¿Qué tipo de dato usarías para almacenar el número 300?'                           )
   ,(       5                      ,'¿Cuál es el valor mínimo que puede almacenar un byte?'                             );

INSERT INTO Answer
    (   idQuestion                 ,Answer                                                              ,CorrectAnswer) VALUES
    (1                             ,'Atlántico'                                                         ,F)
   ,(1                             ,'Pacífico'                                                          ,T)
   ,(1                             ,'Índico'                                                            ,F)
   ,(1                             ,'Ártico'                                                            ,F)
   ,(2                             ,'Europa'                                                            ,F)
   ,(2                             ,'América'                                                           ,F)
   ,(2                             ,'África'                                                            ,T)
   ,(2                             ,'Asia'                                                              ,F)
   ,(3                             ,'Venus'                                                             ,F)
   ,(3                             ,'Marte'                                                             ,F)
   ,(3                             ,'Mercurio'                                                          ,T)
   ,(3                             ,'Júpiter'                                                           ,F)
   ,(4                             ,'Miguel Ángel'                                                      ,F)
   ,(4                             ,'Leonardo da Vinci'                                                 ,T)
   ,(4                             ,'Botticelli'                                                        ,F)
   ,(4                             ,'Rafael'                                                            ,F)
   ,(5                             ,'Osaka'                                                             ,F)
   ,(5                             ,'Tokio'                                                             ,T)
   ,(5                             ,'Nagoya'                                                            ,F)
   ,(5                             ,'Kioto'                                                             ,F)
   ,(6                             ,'Dióxido de carbono'                                                ,F)
   ,(6                             ,'Oxígeno'                                                           ,T)
   ,(6                             ,'Nitrógeno'                                                         ,F)
   ,(6                             ,'Helio'                                                             ,F)
   ,(7                             ,'Tigre'                                                             ,F)
   ,(7                             ,'León'                                                              ,T)
   ,(7                             ,'Jaguar'                                                            ,F)
   ,(7                             ,'Elefante'                                                          ,F)
   ,(8                             ,'Francia'                                                           ,T)
   ,(8                             ,'Italia'                                                            ,F)
   ,(8                             ,'España'                                                            ,F)
   ,(8                             ,'Alemania'                                                          ,F)
   ,(9                             ,'Nilo'                                                              ,F)
   ,(9                             ,'Amazonas'                                                          ,T)
   ,(9                             ,'Yangtsé'                                                           ,F)
   ,(9                             ,'Misisipi'                                                          ,F)
   ,(10                            ,'Newton'                                                            ,F)
   ,(10                            ,'Einstein'                                                          ,T)
   ,(10                            ,'Galileo'                                                           ,F)
   ,(10                            ,'Tesla'                                                             ,F)
   ,(11                            ,'Lilo & Stitch'                                                     ,T)
   ,(11                            ,'Moana'                                                             ,F)
   ,(11                            ,'Enredados'                                                         ,F)
   ,(11                            ,'Frozen'                                                            ,F)
   ,(12                            ,'Pua'                                                               ,F)
   ,(12                            ,'Pascal'                                                            ,F)
   ,(12                            ,'Flounder'                                                          ,F)
   ,(12                            ,'Dory'                                                              ,T)
   ,(13                            ,'Tiana'                                                             ,F)
   ,(13                            ,'Ariel'                                                             ,F)
   ,(13                            ,'Rapunzel'                                                          ,T)
   ,(13                            ,'Bella'                                                             ,F)
   ,(14                            ,'La Sirenita'                                                       ,F)
   ,(14                            ,'Aladdín'                                                           ,F)
   ,(14                            ,'Hércules'                                                          ,T)
   ,(14                            ,'Mulán'                                                             ,F)
   ,(15                            ,'Bubbles'                                                           ,F)
   ,(15                            ,'Bruce'                                                             ,F)
   ,(15                            ,'Marlin'                                                            ,T)
   ,(15                            ,'Gill'                                                              ,F)
   ,(16                            ,'Sid'                                                               ,F)
   ,(16                            ,'Andy'                                                              ,T)
   ,(16                            ,'Bonnie'                                                            ,F)
   ,(16                            ,'Carl'                                                              ,F)
   ,(17                            ,'Elsa'                                                              ,T)
   ,(17                            ,'Ariel'                                                             ,F)
   ,(17                            ,'Aurora'                                                            ,F)
   ,(17                            ,'Jasmín'                                                            ,F)
   ,(18                            ,'Coco'                                                              ,T)
   ,(18                            ,'Encanto'                                                           ,F)
   ,(18                            ,'Ratatouille'                                                       ,F)
   ,(18                            ,'Soul'                                                              ,F)
   ,(19                            ,'Maléfica'                                                          ,F)
   ,(19                            ,'Cruella de Vil'                                                    ,T)
   ,(19                            ,'Úrsula'                                                            ,F)
   ,(19                            ,'Yzma'                                                              ,F)
   ,(20                            ,'Un dragón'                                                         ,F)
   ,(20                            ,'Un caballo'                                                        ,T)
   ,(20                            ,'Un tigre'                                                          ,F)
   ,(20                            ,'Un búho'                                                           ,F)
   ,(21                            ,'La energía almacenada en un capacitor'                             ,F)
   ,(21                            ,'El flujo de electrones por un conductor'                           ,T)
   ,(21                            ,'La diferencia de potencial entre dos puntos'                       ,F)
   ,(21                            ,'La oposición al paso de la corriente'                              ,F)
   ,(22                            ,'Amperio'                                                           ,F)
   ,(22                            ,'Voltio'                                                            ,F)
   ,(22                            ,'Ohmio'                                                             ,T)
   ,(22                            ,'Watt'                                                              ,F)
   ,(23                            ,'Resistencia y potencia'                                            ,F)
   ,(23                            ,'Voltaje, corriente y resistencia'                                  ,T)
   ,(23                            ,'Capacitancia e inductancia'                                        ,F)
   ,(23                            ,'Voltaje y frecuencia'                                              ,F)
   ,(24                            ,'Resistor'                                                          ,F)
   ,(24                            ,'Inductor'                                                          ,F)
   ,(24                            ,'Diodo'                                                             ,F)
   ,(24                            ,'Capacitor'                                                         ,T)
   ,(25                            ,'Almacenar energía'                                                 ,F)
   ,(25                            ,'Amplificar señales'                                                ,F)
   ,(25                            ,'Permitir el paso de corriente en un solo sentido'                  ,T)
   ,(25                            ,'Reducir voltaje'                                                   ,F)
   ,(26                            ,'P = V / I'                                                         ,F)
   ,(26                            ,'P = V x I'                                                         ,T)
   ,(26                            ,'P = I² / R'                                                        ,F)
   ,(26                            ,'P = R x V'                                                         ,F)
   ,(27                            ,'Henry'                                                             ,F)
   ,(27                            ,'Faradio'                                                           ,T)
   ,(27                            ,'Tesla'                                                             ,F)
   ,(27                            ,'Coulomb'                                                           ,F)
   ,(28                            ,'Corriente continua (DC)'                                           ,F)
   ,(28                            ,'Corriente alterna (AC)'                                            ,T)
   ,(28                            ,'Corriente de fuga'                                                 ,F)
   ,(28                            ,'Corriente de pico'                                                 ,F)
   ,(29                            ,'La corriente se divide en diferentes caminos'                      ,F)
   ,(29                            ,'El voltaje es igual en todos los componentes'                      ,F)
   ,(29                            ,'Los componentes comparten la misma corriente'                      ,T)
   ,(29                            ,'No existe resistencia total'                                       ,F)
   ,(30                            ,'Resistencia'                                                       ,F)
   ,(30                            ,'Capacitancia'                                                      ,F)
   ,(30                            ,'Inductancia'                                                       ,T)
   ,(30                            ,'Conductancia'                                                      ,F)
   ,(31                            ,'Urano'                                                             ,F)
   ,(31                            ,'Neptuno'                                                           ,F)
   ,(31                            ,'Marte'                                                             ,T)
   ,(31                            ,'Tierra'                                                            ,F)
   ,(32                            ,'150,000,000'                                                       ,T)
   ,(32                            ,'100,000'                                                           ,F)
   ,(32                            ,'150,000'                                                           ,F)
   ,(32                            ,'100,000,000'                                                       ,F)
   ,(33                            ,'Tierra'                                                            ,F)
   ,(33                            ,'Mercurio'                                                          ,F)
   ,(33                            ,'Urano'                                                             ,F)
   ,(33                            ,'Jupiter'                                                           ,T)
   ,(34                            ,'89'                                                                ,F)
   ,(34                            ,'7F'                                                                ,T)
   ,(34                            ,'95'                                                                ,F)
   ,(34                            ,'1F'                                                                ,F)
   ,(35                            ,'Venus'                                                             ,F)
   ,(35                            ,'Mercurio'                                                          ,T)
   ,(35                            ,'Tierra'                                                            ,F)
   ,(35                            ,'Saturno'                                                           ,F)
   ,(36                            ,'M'                                                                 ,F)
   ,(36                            ,'G'                                                                 ,T)
   ,(36                            ,'K'                                                                 ,F)
   ,(36                            ,'O'                                                                 ,F)
   ,(37                            ,'El punto intermedio entre el punto más lejano y cercano'           ,F)
   ,(37                            ,'El punto mas cercano'                                              ,F)
   ,(37                            ,'El punto mas lejano'                                               ,T)
   ,(37                            ,'La distancia no existe, es producto de tu imaginación'             ,F)
   ,(38                            ,'Saturno'                                                           ,F)
   ,(38                            ,'Jupiter'                                                           ,F)
   ,(38                            ,'Neptuno'                                                           ,T)
   ,(38                            ,'Pluton'                                                            ,F)
   ,(39                            ,'Ceres'                                                             ,T)
   ,(39                            ,'Xenor'                                                             ,F)
   ,(39                            ,'Gesto'                                                             ,F)
   ,(39                            ,'Etumu'                                                             ,F)
   ,(40                            ,'Pluton'                                                            ,F)
   ,(40                            ,'Mercurio'                                                          ,T)
   ,(40                            ,'Tierra'                                                            ,F)
   ,(40                            ,'Venus'                                                             ,F)
   ,(41                            ,'String'                                                            ,F)
   ,(41                            ,'Integer'                                                           ,F)
   ,(41                            ,'double'                                                            ,T)
   ,(41                            ,'Scanner'                                                           ,F)
   ,(42                            ,'8 bits'                                                            ,F)
   ,(42                            ,'16 bits'                                                           ,F)
   ,(42                            ,'32 bits'                                                           ,T)
   ,(42                            ,'64 bits'                                                           ,F)
   ,(43                            ,'String'                                                            ,F)
   ,(43                            ,'char'                                                              ,T)
   ,(43                            ,'Character'                                                         ,F)
   ,(43                            ,'byte'                                                              ,F)
   ,(44                            ,'true'                                                              ,F)
   ,(44                            ,'false'                                                             ,T)
   ,(44                            ,'0'                                                                 ,F)
   ,(44                            ,'null'                                                              ,F)
   ,(45                            ,'short'                                                             ,F)
   ,(45                            ,'byte'                                                              ,F)
   ,(45                            ,'long'                                                              ,T)
   ,(45                            ,'float'                                                             ,F)
   ,(46                            ,'long'                                                              ,F)
   ,(46                            ,'float'                                                             ,T)
   ,(46                            ,'short'                                                             ,F)
   ,(46                            ,'boolean'                                                           ,F)
   ,(47                            ,'char[]'                                                            ,F)
   ,(47                            ,'String'                                                            ,T)
   ,(47                            ,'Character'                                                         ,F)
   ,(47                            ,'Text'                                                              ,F)
   ,(48                            ,'boolean'                                                           ,F)
   ,(48                            ,'char'                                                              ,F)
   ,(48                            ,'double'                                                            ,F)
   ,(48                            ,'String'                                                            ,T)
   ,(49                            ,'byte'                                                              ,F)
   ,(49                            ,'short'                                                             ,T)
   ,(49                            ,'int'                                                               ,F)
   ,(49                            ,'boolean'                                                           ,F)
   ,(50                            ,'0'                                                                 ,F)
   ,(50                            ,'-128'                                                              ,T)
   ,(50                            ,'-255'                                                              ,F)
   ,(50                            ,'-32768'                                                            ,F);